# Generated by Django 3.2.3 on 2021-05-26 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210525_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='tutorial_slug',
            new_name='category_summary',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='tutorial_summary',
            new_name='series_summary',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_pulished',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_series',
        ),
        migrations.RemoveField(
            model_name='tutorialcategory',
            name='tutorial_summary',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialcategory',
            name='category_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
